; Listing generated by Microsoft (R) Optimizing Compiler Version 19.44.35211.0 

include listing.inc

INCLUDELIB MSVCRT
INCLUDELIB OLDNAMES

PUBLIC	main
pdata	SEGMENT
$pdata$main DD	imagerel $LN5
	DD	imagerel $LN5+107
	DD	imagerel $unwind$main
pdata	ENDS
_DATA	SEGMENT
$SG8130	DB	'H', 00H, 'e', 00H, 'l', 00H, 'l', 00H, 'o', 00H, ' ', 00H
	DB	'W', 00H, 'o', 00H, 'r', 00H, 'l', 00H, 'd', 00H, '!', 00H, 0dH
	DB	00H, 0aH, 00H, 00H, 00H
_DATA	ENDS
xdata	SEGMENT
$unwind$main DD	010e01H
	DD	0420eH
xdata	ENDS
; Function compile flags: /Odtpy
_TEXT	SEGMENT
ImageHandle$ = 48
SystemTable$ = 56
main	PROC
; File H:\source\OS-dev\src\main.c
; Line 5
$LN5:
	mov	QWORD PTR [rsp+16], rdx
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 40					; 00000028H
; Line 6
	mov	rax, QWORD PTR SystemTable$[rsp]
	mov	rax, QWORD PTR [rax+64]
	xor	edx, edx
	mov	rcx, QWORD PTR SystemTable$[rsp]
	mov	rcx, QWORD PTR [rcx+64]
	call	QWORD PTR [rax]
; Line 7
	mov	rax, QWORD PTR SystemTable$[rsp]
	mov	rax, QWORD PTR [rax+64]
	mov	edx, 2
	mov	rcx, QWORD PTR SystemTable$[rsp]
	mov	rcx, QWORD PTR [rcx+64]
	call	QWORD PTR [rax+40]
; Line 8
	mov	rax, QWORD PTR SystemTable$[rsp]
	mov	rax, QWORD PTR [rax+64]
	lea	rdx, OFFSET FLAT:$SG8130
	mov	rcx, QWORD PTR SystemTable$[rsp]
	mov	rcx, QWORD PTR [rcx+64]
	call	QWORD PTR [rax+8]
	npad	1
$LN2@main:
; Line 10
	xor	eax, eax
	cmp	eax, 1
	je	SHORT $LN3@main
	jmp	SHORT $LN2@main
$LN3@main:
; Line 12
	xor	eax, eax
; Line 13
	add	rsp, 40					; 00000028H
	ret	0
main	ENDP
_TEXT	ENDS
END
